---
name: 'OPI Integration CI'

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'integration/**'
      - '.github/workflows/poc-integration.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'integration/**'
      - '.github/workflows/poc-integration.yml'

concurrency:
  # if workflow for PR or push is already running stop it, and start new one
  group: poc-integration-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run_integration_poc:
    runs-on: ubuntu-latest
    steps:
    - name: configure HUGE pages
      run: |
        sync
        echo 1 | sudo tee /proc/sys/vm/drop_caches
        sudo mkdir -p /mnt/huge
        grep hugetlbfs /proc/mounts || sudo mount -t hugetlbfs nodev /mnt/huge
        echo 1024 | sudo tee /proc/sys/vm/nr_hugepages
        echo "Check and fail if not enough"
        grep 1024 /sys/kernel/mm/hugepages/hugepages-2048kB/nr_hugepages

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Start containers
      run: ./scripts/integration.sh start
      working-directory: integration

    - name: Run Integration Tests
      run: ./scripts/integration.sh tests
      working-directory: integration

    - name: Logs
      if: failure()
      run: ./scripts/integration.sh logs
      working-directory: integration

    - name: Stop containers
      if: always()
      run: ./scripts/integration.sh stop
      working-directory: integration
