---
name: 'OPI Security PoC CI'

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'security/**'
      - '.github/workflows/poc-security.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'security/**'
      - '.github/workflows/poc-security.yml'

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io

concurrency:
  # if workflow for PR or push is already running stop it, and start new one
  group: poc-security-${{ github.ref }}
  cancel-in-progress: true

jobs:
  security-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - server
          - client
    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-qemu-action@v2
    - uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf

    - name: Log into registry ${{ env.REGISTRY }}
      if: github.event_name != 'pull_request'
      uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/opi-security-${{ matrix.package }}

    - name: Build and push Docker image
      id: build-and-push
      uses: docker/build-push-action@c84f38281176d4c9cdb1626ffafcd6b3911b5d94
      with:
        context: security/${{ matrix.package }}
        platforms: linux/amd64,linux/arm64
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

  security-ci:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    # Workaround: https://github.com/docker/build-push-action/issues/461
    - name: Setup Docker buildx
      uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf

    - name: Start containers
      run: docker-compose up -d
      working-directory: security

    - name: Run Tests
      run: |
        docker-compose ps
        docker-compose run opi-security-client
      working-directory: security

    - name: Logs
      if: failure()
      run: docker-compose logs
      working-directory: security

    - name: Stop containers
      if: always()
      run: docker-compose down
      working-directory: security
