---
name: 'OPI Storage PoC CI'

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'storage/**'
      - '.github/workflows/poc-storage.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'storage/**'
      - '.github/workflows/poc-storage.yml'

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository_owner }}/opi-spdk

concurrency:
  # if workflow for PR or push is already running stop it, and start new one
  group: poc-storage-${{ github.ref }}
  cancel-in-progress: true

jobs:
  storage-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - server
          - client
    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-qemu-action@v2
    - uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf

    - name: Log into registry ${{ env.REGISTRY }}
      if: github.event_name != 'pull_request'
      uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/opi-storage-${{ matrix.package }}

    - name: Build and push Docker image
      id: build-and-push
      uses: docker/build-push-action@c84f38281176d4c9cdb1626ffafcd6b3911b5d94
      with:
        context: storage/${{ matrix.package }}
        platforms: linux/amd64,linux/arm64
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

  docker-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    # Workaround: https://github.com/docker/build-push-action/issues/461
    - name: Setup Docker buildx
      uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf

    # Login against a Docker registry except on PR
    # https://github.com/docker/login-action
    - name: Log into registry ${{ env.REGISTRY }}
      uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Extract metadata (tags, labels) for Docker
    # https://github.com/docker/metadata-action
    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@69f6fc9d46f2f8bf0d5491e4aabe0bb8c6a4678a
      with:
        sep-tags: ","
        sep-labels: ","
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        # Docker tags based on the following events/attributes
        tags: |
          type=schedule
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=sha

    # Build and push Docker image with Buildx
    # https://github.com/docker/build-push-action
    - name: Build Docker image
      id: build
      uses: docker/build-push-action@c84f38281176d4c9cdb1626ffafcd6b3911b5d94
      with:
        context: storage
        push: false
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        outputs: type=docker,dest=/tmp/myimage.tar
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Load docker image locally
      run: docker image load < /tmp/myimage.tar
      working-directory: storage

    - name: List docker images
      run: docker image ls
      working-directory: storage

    - name: Start containers
      run: SPDK_TAG=sha-$(git rev-parse --short ${{ github.sha }}) ./scripts/poc.sh start
      working-directory: storage

    - name: Run Tests
      run: SPDK_TAG=sha-$(git rev-parse --short ${{ github.sha }}) ./scripts/poc.sh tests
      working-directory: storage

    - name: Logs
      if: failure()
      run: ./scripts/poc.sh logs
      working-directory: storage

    - name: Stop containers
      if: always()
      run: ./scripts/poc.sh stop
      working-directory: storage

    - name: Upload build artifact
      if: github.event_name == 'pull_request'
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.os }}-${{ steps.system.outputs.arch }}
        path: /tmp/myimage.tar
        retention-days: 1

    # Build and push Docker image with Buildx
    # https://github.com/docker/build-push-action
    # NOTE: The second time we run this, the iamge should already be
    # built, and we're just doing the push to ghcr.io
    - name: Push Docker image
      id: push-to-ghcr
      uses: docker/build-push-action@c84f38281176d4c9cdb1626ffafcd6b3911b5d94
      if: github.event_name != 'pull_request'
      with:
        context: storage
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
